import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";

const outfit = Outfit({
	variable: "--font-outfit",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${outfit.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
